image: ruby:2.4

pipelines:
  default:
    - step:
        name: Build package
        caches:
          - bundler
        script:
          - ruby --version
          - bundle install --path ./vendor
          - bundle exec rake build
    - step:
        name: Generate documentation
        caches:
          - bundler
        script:
          - bundle install --path ./vendor
          - bundle exec rake yard
          - bundle exec rake rubocop
          - bundle exec rake spec
    - step:
        name: Rubocop
        caches:
          - bundler
        script:
          - ruby --version
          - bundle install --path ./vendor
          - bundle exec rake rubocop
    - step:
        name: Run tests
        deployment: test
        caches:
          - bundler
        script:
          - bundle install --path ./vendor
          - bundle exec rake spec

definitions:
  caches:
    bundler: ./vendor
